### ISSUE TITLE
fix(payumoney): ensure the payment gateway can be enabled from the settings

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give-payumoney#12]
## User Story
As a `site admin, I want `to activate the PayUmoney gateway from the Payment Gateways settings page` so that `my donors can give through this payment gateway`.

## Current Behavior
I currently can't activate PayUmoney from the Payment Gateways settings pages. It is also not showing up as an option in on the front-end of my site, making the payment gateway completely unusable.

## Expected Behavior
I expect to activate the payment gateway and have my donors use it on the front of my site.

## Steps to Reproduce
1. Activate the PayUmoney addon
2. Attempt to activate the payment gateway from the Payment Gateways settings page
3. When you hit save it doesn't activate the gateway, and isn't visible from the form page.

## Visuals
![screen shot 2018-09-24 at 11 19 51 am](https://user-images.githubusercontent.com/20672471/45961134-d1a0db80-bfeb-11e8-814d-b1a41d49bb0d.png)

Screencast of the issue:
https://screencast-o-matic.com/watch/cFQZo3YczY

## Related
https://secure.helpscout.net/conversation/670407007/26125

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: https://give.gsamsmith.com
Site URL: https://give.gsamsmith.com
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: 4b8_
Table Prefix Length: 4
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.gsamsmith.com
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache
PHP Version: 7.0.32
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
PHP Max Upload Size: 64 MB
cURL Version: 7.61.0, OpenSSL/1.0.2p
SUHOSIN Installed: –
MySQL Version: 5.6.41
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.2.5
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Completed Email✔Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: 2.2.4
Test Mode: Enabled
Currency Code: GBP
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://give.gsamsmith.com/donation-confirmation/
Failure Page: https://give.gsamsmith.com/donation-failed/
Donation History Page: https://give.gsamsmith.com/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: PayPal Standard, Offline Donation, Authorize.net
Default Payment Gateway: Offline Donation
PayPal IPN Verification: Disabled
PayPal IPN Notifications: IPN received for #303 ( 6JM78069A3740351G ) on 08/29/2018 at 06:17. Status N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - 2Checkout Gateway: ❌ Unlicensed – by WordImpress – 1.1.2
Give - Authorize.net Gateway: ✔ Licensed – by WordImpress – 1.4.3
Give - Form Field Manager: ✔ Licensed – by WordImpress – 1.3
Give - Gift Aid: ✔ Licensed – by WordImpress – 1.1.6
Give - Manual Donations: ✔ Licensed – by WordImpress – 1.4.1
Give - PayFast Payment Gateway: ❌ Unlicensed – by WordImpress – 1.0.2
Give - PayUmoney: ❌ Unlicensed – by WordImpress – 1.0.1
Give - PDF Receipts: ❌ Unlicensed – by WordImpress – 2.3
Give - Recurring Donations: ✔ Licensed – by WordImpress – 1.8.0
Give - Tributes: ✔ Licensed – by WordImpress – 1.5.0
Give - Zapier: ✔ Licensed – by WordImpress – 1.2.1

### Other Active Plugins ###

Email Cop: by Ashfame – 0.1.1
Give - Fee Recovery: by GiveWP – 1.7.2
Give - PayPal Pro Gateway: by GiveWP – 1.2.0
Give - Stripe Gateway: by GiveWP – 2.1.0
Query Monitor: by John Blackbourn & contributors – 3.1.1
Transients Manager: by Pippin Williamson – 1.7.5
WP Rollback: by WordImpress – 1.5.1

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.0.8
Debug Bar: by wordpressdotorg – 0.9
Give - 2Checkout Gateway: by WordImpress – 1.1.1
Give - AmeriCloud Payments: by AmeriCloud Solutions, Inc. – 1.2.0
Give - AWeber: by WordImpress – 1.0.3
Give - Braintree Gateway: by WordImpress – 1.2.2
Give - CCAvenue Gateway: by WordImpress – 1.0.2
Give - Constant Contact: by WordImpress – 1.2.1
Give - ConvertKit: by WordImpress – 1.0.2
Give - CSV Toolbox: by WordImpress – 1.0
Give - Currency Switcher: by WordImpress – 1.2.2
Give - Dwolla Gateway: by WordImpress – 1.1.2
Give - Email Reports: by WordImpress – 1.1.2
Give - GoCardless Gateway: by WordImpress – 1.2
Give - Google Analytics Donation Tracking: by WordImpress – 1.1.4
Give - iATS Payment Solutions: by WordImpress – 1.0.3
Give - MailChimp: by WordImpress – 1.4.1
Give - Mollie Gateway: by WordImpress – 1.1.1
Give - Paymill Gateway: by WordImpress – 1.0.2
Give - Paytm Gateway: by WordImpress – 1.0
Give - Per Form Gateways: by WordImpress – 1.0.1
Give - Razorpay: by WordImpress – 1.2.0
Give - Sofort Payment Gateway: by WordImpress, CoachBirgit – 1.0
Gutenberg: by Gutenberg Team – 3.8.0

### Active MU Plugins ###

Endurance PHP Edge: by Mike Hansen – 0.2
SSO: by Garth Mortensen, Mike Hansen – 0.3

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

**Comment by mehul0810** [comment]
@samsmith89 Currently, PayUMoney support INR currency only so when you try to enable the payment gateway with any other base currency then it will show you notice as below. I can see the same notice in your attached video.

![image](https://user-images.githubusercontent.com/1852711/46271487-7d0cdb80-c56a-11e8-8af8-c777fc7c3d7c.png)

Let's discuss this issue when you come online.

**Comment by mehul0810** [comment]
Closing this issue as we can only support INR with PayUMoney add-on as per the reply received from PayUMoney support. Please check below screenshot.

![image](https://user-images.githubusercontent.com/1852711/46287674-e576af80-c5a0-11e8-960c-5688479326d8.png)
