### ISSUE TITLE
fix: ensure testing credentials do not produce an error at the payment gateway

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give-payumoney#15]
# Bug Report

## User Story

As a site admin, I want to test my site with the PayUmoney payment gateway so that I can know if it works before taking it live.

## Current Behavior
I receive an error from the payment gateway saying that my testing credentials aren't correct. Even though I confirmed they work.

## Expected Behavior

I expect to test the payment gateway successfully before taking it live. 

## Bug Type
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Configure a site with PayUmoney testing credentials. 
2. Submit a donation with the PayUmoney gateway
3. See there error page you're redirected to

Here is a link to a form on a live site with the testing credentials in place:
https://give.gsamsmith.com/donations/payumoney/

## Visuals

![screen shot 2018-12-03 at 10 45 32 am](https://user-images.githubusercontent.com/20672471/49384702-8d1b7580-f6e9-11e8-9d96-309eaa3ebb17.png)

## Related

https://secure.helpscout.net/conversation/720727207/30229/
https://secure.helpscout.net/conversation/733861448/31234/

## Acceptance Criteria

- [x] Investigate the issue
- [x] Review the integration document
- [x] I can submit a donation while using testing credentials with PayUmoney
- [x] Testing

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: https://give.gsamsmith.com
Site URL: https://give.gsamsmith.com
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: 4b8_
Table Prefix Length: 4
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.gsamsmith.com
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache
PHP Version: 7.0.32
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
PHP Max Upload Size: 64 MB
cURL Version: 7.62.0, OpenSSL/1.0.2p
SUHOSIN Installed: –
MySQL Version: 5.6.41
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.3.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Completed Email✔Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: 2.2.4
Test Mode: Enabled
Currency Code: INR
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://give.gsamsmith.com/donation-confirmation/
Failure Page: https://give.gsamsmith.com/donation-failed/
Donation History Page: https://give.gsamsmith.com/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Credit Card, Test Donation, PayUmoney
Default Payment Gateway: Test Donation
PayPal IPN Verification: Disabled
PayPal IPN Notifications: IPN received for #559 ( 06V14366UX708703B ) on 11/15/2018 at 09:38. Status N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ❌ Unlicensed – by WordImpress – 1.4.3
Give - Currency Switcher: ❌ Unlicensed – by GiveWP – 1.3.0
Give - Donation Upsells for WooCommerce: ❌ Unlicensed – by WordImpress – 1.0.4
Give - Email Reports: ❌ Unlicensed – by WordImpress – 1.1.2
Give - Fee Recovery: ❌ Unlicensed – by GiveWP – 1.7.2
Give - Form Field Manager: ❌ Unlicensed – by GiveWP – 1.4.1
Give - Gift Aid: ✔ Licensed – by WordImpress – 1.1.6
Give - GoCardless Gateway: ✔ Licensed – by WordImpress – 1.2.1
Give - Google Analytics Donation Tracking: ❌ Unlicensed – by GiveWP – 1.2.1
Give - iATS Payment Solutions: ❌ Unlicensed – by GiveWP – 1.0.4
Give - MailChimp: ❌ Unlicensed – by WordImpress – 1.4.1
Give - Mollie Gateway: ❌ Unlicensed – by WordImpress – 1.1.2
Give - PayFast Payment Gateway: ❌ Unlicensed – by WordImpress – 1.0.2
Give - PayPal Pro Gateway: ❌ Unlicensed – by GiveWP – 1.2.0
Give - PayUmoney: ❌ Unlicensed – by GiveWP – 1.0.2
Give - PDF Receipts: ❌ Unlicensed – by WordImpress – 2.3
Give - Per Form Gateways: ❌ Unlicensed – by WordImpress – 1.0.1
Give - Recurring Donations: ❌ Unlicensed – by GiveWP – 1.8.2
Give - Stripe Gateway: ❌ Unlicensed – by GiveWP – 2.1.2
Give - Tributes: ✔ Licensed – by WordImpress – 1.5.0
Give - Zapier: ✔ Licensed – by WordImpress – 1.2.1
WP Rollback: ❌ Unlicensed – by WordImpress – 1.5.1

### Other Active Plugins ###

All-in-One WP Migration: by ServMask – 6.78
Contact Form 7: by Takayuki Miyoshi – 5.0.4
Email Cop: by Ashfame – 0.1.1
Give - Sofort Payment Gateway: by WordImpress, CoachBirgit – 1.0
My Custom Functions: by Space X-Chimp – 4.31
Query Monitor: by John Blackbourn & contributors – 3.1.1
Transients Manager: by Pippin Williamson – 1.7.5

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.0.8
Debug Bar: by wordpressdotorg – 0.9
Give - 2Checkout Gateway: by WordImpress – 1.1.2
Give - AmeriCloud Payments: by AmeriCloud Solutions, Inc. – 1.2.0
Give - AWeber: by WordImpress – 1.0.3
Give - Braintree Gateway: by WordImpress – 1.2.2
Give - CCAvenue Gateway: by WordImpress – 1.0.2
Give - Constant Contact: by WordImpress – 1.2.1
Give - ConvertKit: by WordImpress – 1.0.2
Give - CSV Toolbox: by WordImpress – 1.0
Give - Dwolla Gateway: by WordImpress – 1.1.2
Give - Manual Donations: by GiveWP – 1.4.2
Give - Paymill Gateway: by WordImpress – 1.0.2
Give - Paytm Gateway: by WordImpress – 1.0
Give - Razorpay: by WordImpress – 1.2.0
Gutenberg: by Gutenberg Team – 3.8.1
Head and Footer Scripts Inserter: by Space X-Chimp – 4.33
Invisible reCaptcha: by Mihai Chelaru – 1.2.1
WooCommerce: by Automattic – 3.5.1

### Active MU Plugins ###

Endurance PHP Edge: by Mike Hansen – 0.2
SSO: by Garth Mortensen, Mike Hansen – 0.3

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by kevinwhoffman** [comment]
@ravinderk Per discussion, prioritize this after the next batch of releases.

**Comment by mehul0810** [comment]
## Slack Call Summary
Participants: @mehul0810 @ravinderk 
Topic: Discussion on my findings and removal of service provider
Result: I've noticed that we have removed service provider parameter as a part of some other HS ticket which is now causing issues with other customers. I'll review the HS tickets in which it was removed and will add the service_provider parameter back if it is good to add it back.

**Comment by ravinderk** [comment]
*Slack Call Summary*
Participants: @mehul0810 @ravinderk 
Topic: Discussion on PayUMoney and PayUBiz confusion
Result: We’ll discuss our query on weekly call tomorrow to finalize the solution to whether we need to support PayUBiz or not. And if there is any existing customer for PayUBiz then what we need to answer them.

**Comment by kevinwhoffman** [comment]
## Slack Call Summary

Participants: Dev Team
Topic: How to handle PayUmoney and PayUbiz
Result: @mehul0810 will research PayUbiz implementation and provide an updated estimate and acceptance criteria for integrating it in the plugin. https://documentation.payubiz.in/
