### ISSUE TITLE
Having issue with payment. After payment website get stopped at domin.org/file/?process_payu_payment=success [Broken functionality] should...

### ISSUE THREAD

**Issue by amaravindmenon** [impress-org/give-payumoney#28]
Having issue with payment. After payment website get stopped at domin.org/file/?process_payu_payment=success

## User Story

As a [type of user], I want [some goal] so that [some reason].

## Steps to Reproduce

1. Go to...
2. Select...
3. Scroll down to...
4. View error

## System Information

<details><summary>Details</summary>

</details>

## Acceptance Criteria

-   [ ] Something happens when an action is taken.
-   [ ] Something does not happen when an action is taken.
-   [ ] Fixing behavior in Component A does not affect existing behavior in Component B.

**Comment by kjohnson** [comment]
@amaravindmenon I'm sorry to hear that you are having an issue with processing payments with PayU. From what I can tell the best place for this report is the [GiveWP Support](https://givewp.com/support/) channel or the [GiveWP Feedback](https://feedback.givewp.com/bug-reports)  channel - there our team is prepared to address these sort of issues. This repository is intended for planned development tasks and new reports need to be investigated before we can process anything here.

- https://givewp.com/support/
- https://feedback.givewp.com/bug-reports
